version: '3.2'
services:
  salt:
    build:
      context: .
      dockerfile: Dockerfile.master
    image: datica/salt-master:file_roots
    volumes:
      - ./salt:/usr/local/salt
  minion1:
    build:
      context: .
      dockerfile: Dockerfile.minion1
    image: datica/salt-minion:minion1
  minion2:
    build:
      context: .
      dockerfile: Dockerfile.minion2
    image: datica/salt-minion:minion2
  minion3:
    build:
      context: .
      dockerfile: Dockerfile.minion3
    image: datica/salt-minion:minion3

