version: '3.2'
services:
  salt:
    image: datica/salt-master
    volumes:
      - ./configs/master:/etc/salt/master
      - ./salt:/usr/local/salt
      - ./pillar:/usr/local/pillar
  minion1:
    image: datica/salt-minion
    volumes:
      - ./configs/minion1.minion_id:/etc/salt/minion_id
  minion2:
    image: datica/salt-minion
    volumes:
      - ./configs/minion2.minion_id:/etc/salt/minion_id
  minion3:
    image: datica/salt-minion
    volumes:
      - ./configs/minion3.minion_id:/etc/salt/minion_id

