version: '3'
services:
  salt:
    build:
      context: .
      dockerfile: Dockerfile.master
    image: 'datica/salt-master:auto_accept_true'
  minion1:
    environment:
      NAME: minion1
    build:
      context: .
      dockerfile: Dockerfile.minion
    image: 'datica/salt-minion:client_name'
  minion2:
    environment:
      NAME: minion2
    build:
      context: .
      dockerfile: Dockerfile.minion
    image: 'datica/salt-minion:client_name'
  minion3:
    environment:
      NAME: minion3
    build:
      context: .
      dockerfile: Dockerfile.minion
    image: 'datica/salt-minion:client_name'
