version: '3'
services:
  salt:
    image: 'datica/salt-master:auto_accept_true'
  minion1:
    image: 'datica/salt-minion'
  minion2:
    image: 'datica/salt-minion'
  minion3:
    image: 'datica/salt-minion'
