version: '3.2'
services:
  salt:
    image: datica/salt-master
    volumes:
      - ./configs/master:/etc/salt/master
      - ./salt:/usr/local/salt
  minion1:
    volumes:
      - ./configs/minion1.minion_id:/etc/salt/minion_id
    image: datica/salt-minion
  minion2:
    volumes:
      - ./configs/minion2.minion_id:/etc/salt/minion_id
    image: datica/salt-minion
  minion3:
    volumes:
      - ./configs/minion3.minion_id:/etc/salt/minion_id
    image: datica/salt-minion

